# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Youth' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Youth
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'YouthTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YouthUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
